###SIGNUP
POST http://localhost:5000/api/auth/signUp
Content-Type: application/json

{
    "firstName":"jhon",
     "lastName":"bill", 
     "email":"jhon111@gmail.com", 
     "password":"123456"
}

###lOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
     "email":"jhon111@gmail.com", 
     "password":"123456"
    
}
